### ISSUE TITLE
Complex keys

### ISSUE THREAD

**Issue by wesleytodd** [0x00A/level-mget#1]
This module currently only supports simple string keys.  As leveldb supports complex key types, it would be nice to also support them here. 

I can put together a PR that uses a `Map` to represent the return values, if that is something you would be interested in let me know.

Example:

```javascript
mget(db, [['namespace', 'key']], function (err, vals) {
  console.log(vals); // Map{['namespace', 'key']: 'value'}
});
```

**Comment by heapwolf** [comment]
Agreed. That would be nice. A PR would be welcome!
